export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { AuthProvider } from "./AuthContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      <body>
        {" "}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
