export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { ChakraProvider } from "@chakra-ui/react";
import { AuthProvider } from "./AuthContext";
import "@/styles/globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      <body>
        <ChakraProvider>
          {" "}
          <AuthProvider>{children}</AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
